### ISSUE TITLE
core: scratch build.bash not present on x64

### ISSUE THREAD

**Issue by ohadln** [paralin/SkiffOS#15]
Start script cannot find scratchbuild.bash, thus the core docker container cannot be loaded and initialization fails.
Compiled as intel x64 with the following file(configs/intel/x64/buildroot/iso):

BR2_TARGET_ROOTFS_ISO9660=y
BR2_TARGET_GRUB=y

**Comment by paralin** [comment]
Scrach build is provided here: https://github.com/paralin/scratchbuild/blob/master/scratchbuild.bash

The script is not actually useful on x86 since most Docker images on the Docker Hub are built against x86. The script probably should be modified to do nothing against x86.

I'm planning to replicate your setup tonight or tomorrow. In the meantime, you can bypass this entire problem by running the following command on your running system:

```
printf "#!/bin/bash\ndocker pull $2" > /opt/skiff/scripts/scratchbuild.bash
```

Please let me know if that fixes your issue for now.

**Comment by ohadln** [comment]
Hi, the workaround is not possible, as the VM does not reach a prompt at all, see attached screenshot.

![skiff](https://cloud.githubusercontent.com/assets/28089288/25953689/c693ebb0-366c-11e7-9ddf-80a842ae3bea.png)

**Comment by paralin** [comment]
Are you certain? Try SSHing to root. At that stage it should have already completed boot. You're just watching the system logs.

**Comment by paralin** [comment]
You are setting BR2_TARGET_GRUB but BR2_TARGET_GRUB2 is already enabled - do you need both? Why?

**Comment by ohadln** [comment]
Hi Christian, I don't need both - just GRUB. I'm not sure though how to disable GRUB2.

**Comment by paralin** [comment]
`BR2_PACKAGE_GRUB2=n`

**Comment by paralin** [comment]
Superseded: #26
