### ISSUE TITLE
Please create a tag / release for the project

### ISSUE THREAD

**Issue by ohadln** [paralin/SkiffOS#32]
Hi, I want to clone a specific version of SkiffOS, so tests can be effective. For that tag / release version is needed.

Thanks!

**Comment by paralin** [comment]
You can just clone a specific commit hash - i.e. cab2645f2195df46e0e657263181d16417624437

https://github.com/paralin/SkiffOS/commit/cab2645f2195df46e0e657263181d16417624437

Because of the nature of Skiff, it's hard to pin specific versions on it at different times. I will add a release scheme eventually, but for now it would be counterproductive
